# Generated by Django 4.0.3 on 2022-05-11 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='salesperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson', to='sales_rest.salesperson'),
            preserve_default=False,
        ),
    ]
