# Generated by Django 4.0.3 on 2022-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_is_finished_appointment_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin_num',
            field=models.CharField(max_length=17),
        ),
    ]
